services:

  reverseproxy:
    image: nginx
    ports:
      - "443:443" 
      - "80:80" 
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./ssl/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - social-media-app-frontend
    networks:
      - frontend

  social-media-app-frontend:
    container_name: social-media-app-frontend
    image: frontend:latest
    build:
      context: .
      dockerfile: Dockerfile_frontend
    depends_on:
      - social-media-app-backend
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  social-media-app-backend:
    container_name: social-media-app-backend
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile_backend
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - backend

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes: 
      - mongodata:/data/db
    networks:
      - backend
    environment:
      - MONGO_INITDB_DATABASE=mern

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - backend
      - frontend
    
volumes:
  mongodata:

networks:
  backend:
    internal: true
  frontend: